apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: plx-cit-server
spec:
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10G
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets
  namespace: plx-cit-server
spec:
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10G
  accessModes:
    - ReadWriteOnce