name: Build image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Building and pushing container image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/krekka/cit-server-backend:${{ github.sha }}
          platforms: linux/arm64,linux/amd64
